
num_vec <- c(1, 2, 3, 4, 5)
char_vec <- c("a", "b", "c", "d", "e")
log_vec <- c(TRUE, FALSE, TRUE, FALSE, TRUE)
print(num_vec)
print(char_vec)
print(log_vec)
typeof(num_vec)
typeof(char_vec)
typeof(log_vec)
