s <- readline("Enter a string: ")
cat("The unique elements of the string are:\n")
print(unique(s))
v <- sample(1:10, 10, replace = TRUE)
cat("The vector is:\n")
print(v)
cat("The unique numbers of the vector are:\n")
print(unique(v))
